### ISSUE TITLE
Create GoLang handbook

### ISSUE THREAD

**Issue by ajeetraina** [docker-community-leaders/dockercommunity#17]
Start here - https://docker-community-leaders.github.io/dockercommunity/docs/eventhandbooks/golang/

**Comment by sangam14** [comment]
https://docker-community-leaders.github.io/dockercommunity/docs/eventhandbooks/go/

**Comment by ajeetraina** [comment]
@sangam14 Can you please add Recommended Agenda with 8 hour timline.

**Comment by ajeetraina** [comment]
I have added 4 hours agenda

**Comment by ajeetraina** [comment]
@gauravgahlot I saw that you're also working on the same topic and added content. Can you just look at the existing agenda and modify it accordingly.

**Comment by gauravgahlot** [comment]
I was moving the content from root `_index.md` to individual directories. But you already moved it over in master.
So, I will close the PR.

**Comment by ajeetraina** [comment]
Let us keep it open. You can merge your table of contents. They look good.

**Comment by ajeetraina** [comment]
Merged and Fixed.
