### ISSUE TITLE
Logos not consistent and also not clickable

### ISSUE THREAD

**Issue by saiyam1814** [docker-community-leaders/dockercommunity#4]
![image](https://user-images.githubusercontent.com/8190114/105283887-5f4e5f00-5bd7-11eb-918c-2d9104542bda.png)

**Comment by ajeetraina** [comment]
Will try to fix this today.

**Comment by sangam14** [comment]
https://docker-community-leaders.github.io/dockercommunity/ @saiyam1814 ! updated

**Comment by ajeetraina** [comment]
Great work.

**Comment by ajeetraina** [comment]
Fixed.

**Comment by saiyam1814** [comment]
Awesome 👍
