### ISSUE TITLE
Home should display first and then about

### ISSUE THREAD

**Issue by ajeetraina** [docker-community-leaders/dockercommunity#40]
The top menu display "About" and then "Home". It should be in reverse. First "home " and then "about"

**Comment by sangam14** [comment]
sure !

**Comment by sangam14** [comment]
lets chance about page as "welcome " and then "home "

**Comment by ajeetraina** [comment]
Just move Home and about. Let's not add Welcome

**Comment by ajeetraina** [comment]
Fixed.
