### ISSUE TITLE
https://docker-community-leaders.github.io/dockercommunity/blog/

### ISSUE THREAD

**Issue by saiyam1814** [docker-community-leaders/dockercommunity#5]
This page is empty and RSS is pointing to Knative, looks broken.
Also, the post is random 2018
Better to remove if nothing for now
![image](https://user-images.githubusercontent.com/8190114/105284108-c5d37d00-5bd7-11eb-8b50-2d6e08692278.png)
.

**Comment by sangam14** [comment]
feed:https://docker-community-leaders.github.io/dockercommunity/blog/index.xml need to generate feed.xml 

now its linking to feed:https://docker-community-leaders.github.io/dockercommunity/blog/index.xml. to fetch feeds .

**Comment by ajeetraina** [comment]
RSS is fixed.
