### ISSUE TITLE
Remove thick bar from the main page

### ISSUE THREAD

**Issue by ajeetraina** [docker-community-leaders/dockercommunity#80]
@sangam14 Let us try to fix the thick bar which appear on the main page.
Also, we need to add photo onto the main page

**Comment by ajeetraina** [comment]
I just saw that @sangam14  removed 

```
{{% blocks/lead color="primary" %}}

{{% /blocks/lead %}}
```

That does fix the thick bar but doesn't make arrow sign to work.

**Comment by ajeetraina** [comment]
As of now, I have added that back.

**Comment by sangam14** [comment]
Need to add link between both sections.
Let me fix it! 😊

**Comment by ajeetraina** [comment]
I have fixed it.
